version: 2
updates:
  - package-ecosystem: npm
    directories: 
      - "/"
      - "src-admin/"
    schedule:
      interval: cron
      cronjob: 5 4 14 * *
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - ticaki
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: 5 4 14 * *
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - ticaki
