name: Auto Assign Issues/PRs
on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [ready_for_review]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN }}
          # using the `org/team_slug` or `/team_slug` syntax to add git team as reviewers
          reviewers: |
            tt-tom17
            Armilar
            ticaki
          skipKeywords: wip, draft
          numberOfReviewers: 1